export const CHANGE_NODE_TYPE = "CHANGE_NODE_TYPE";
export const CLEAR_GRAPH = "CLEAR_GRAPH";
export const RESET_GRAPH = "RESET_GRAPH";
export const START_ALGORITHM = "START_ALGORITHM";
export const END_ALGORITHM = "END_ALGORITHM";
